export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"项目主页","i":"home"},["/README.md"]],
  ["v-2e3eac9e","/slides.html",{"y":"s","t":"幻灯片页","i":"person-chalkboard"},[":md"]],
  ["v-1473bf53","/demo/",{"y":"a","t":"主要功能与配置演示","i":"laptop-code"},["/demo/README.md"]],
  ["v-4e65ec78","/demo/disable.html",{"y":"a","t":"布局与功能禁用","i":"gears","O":3},[":md"]],
  ["v-c151bf32","/demo/encrypt.html",{"y":"a","t":"密码加密的文章","i":"lock"},[":md"]],
  ["v-438ffe52","/demo/markdown.html",{"y":"a","t":"Markdown 展示","i":"fab fa-markdown","O":2},[":md"]],
  ["v-6e19edb7","/demo/page.html",{"y":"a","t":"页面配置","i":"file","O":1},[":md"]],
  ["v-fffb8e28","/guide/",{"y":"a","t":"指南","i":"lightbulb"},["/guide/README.md"]],
  ["v-5d5c2d30","/guide/bar/",{"y":"a","t":"理论基础","i":"lightbulb"},["/guide/bar/README.md"]],
  ["v-39911380","/guide/bar/maturity.html",{"y":"a","t":"成熟度模型","i":"circle-info"},[":md"]],
  ["v-46c4074e","/guide/bar/white-paper.html",{"y":"a","t":"白皮书","i":"circle-info"},[":md"]],
  ["v-6ce743e8","/guide/product/",{"y":"a","t":"产品先驱","i":"lightbulb"},["/guide/product/README.md"]],
  ["v-029e63dc","/guide/product/kubevela.html",{"y":"a","t":"kubevela","i":"circle-info"},[":md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
]
