export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"项目主页","i":"home"},["/README.md"]],
  ["v-2e3eac9e","/slides.html",{"y":"s","t":"幻灯片页","i":"person-chalkboard"},[":md"]],
  ["v-1473bf53","/demo/",{"y":"a","t":"文档","i":"laptop-code"},["/demo/README.md"]],
  ["v-4e65ec78","/demo/disable.html",{"y":"a","t":"布局与功能禁用","i":"gears","O":3},[":md"]],
  ["v-c151bf32","/demo/encrypt.html",{"y":"a","t":"密码加密的文章","i":"lock"},[":md"]],
  ["v-438ffe52","/demo/markdown.html",{"y":"a","t":"Markdown 展示","i":"fab fa-markdown","O":2},[":md"]],
  ["v-6e19edb7","/demo/page.html",{"y":"a","t":"页面配置","i":"file","O":1},[":md"]],
  ["v-fffb8e28","/guide/",{"y":"a","t":"指南","i":"lightbulb"},["/guide/README.md"]],
  ["v-3166d577","/guide/1.%E7%90%86%E8%AE%BA/maturity.html",{"y":"a","t":"成熟度模型","i":"circle-info","O":2},["/guide/1.理论/maturity.html","/guide/1.理论/maturity.md",":md"]],
  ["v-9e5639fc","/guide/1.%E7%90%86%E8%AE%BA/white-paper.html",{"y":"a","t":"白皮书","i":"circle-info","O":1},["/guide/1.理论/white-paper.html","/guide/1.理论/white-paper.md",":md"]],
  ["v-62bd30ca","/guide/2.%E4%BA%A7%E5%93%81/kubevela.html",{"y":"a","t":"kubevela","i":"circle-info"},["/guide/2.产品/kubevela.html","/guide/2.产品/kubevela.md",":md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
  ["v-31d57bde","/guide/1.%E7%90%86%E8%AE%BA/",{"y":"p","t":"1.理论"},["/guide/1.理论/"]],
  ["v-8405b344","/guide/2.%E4%BA%A7%E5%93%81/",{"y":"p","t":"2.产品"},["/guide/2.产品/"]],
]
